version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "8905:8905"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm run dev
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "8904:8904"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: pnpm run dev
    environment:
      - NODE_ENV=development
