version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "8905:8905"
    environment:
      - NODE_ENV=production
    command: pnpm run prod

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "8904:8904"
    environment:
      - NODE_ENV=production
    command: pnpm run prod
